### ISSUE TITLE
Checking for new documentation is failing

### ISSUE THREAD

**Issue by Aldaviva** [Aldaviva/CSxAPI#4]
```text
> C:\Programs\Accessories\CiscoEndpointDocumentationReleaseIssueCreator.exe --github-access-token ghp_xxx
Checking version of latest documented release...
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at IssueCreator.IssueCreator.findLatestDocumentation()
   at IssueCreator.IssueCreator.CreateIssueIfMissing()
   at IssueCreator.IssueCreator.Main(String[] args)
   at IssueCreator.IssueCreator.<Main>(String[] args)
```

**Comment by Aldaviva** [comment]
This was caused by the `User-Agent` request header value causing a 403 error. Changed header value to get 200.
